
platforms:
  android:
    appName: Capacitor App
    packageName: boy
    versionName: 1.0.0
    versionCode: 1
    manifest:
     - file: AndroidManifest.xml
       target: 'manifest'
       attrs:
         package: boy
    gradle:
     - file: app/build.gradle
       target:
         android:
           namespace:
       replace:
         namespace: boy
    xml:
     - resFile: values/strings.xml
       target: resources/string[@name="app_name"]
       replace: |
         <string name="app_name">Capacitor App</string>

     - resFile: values/strings.xml
       target: resources/string[@name="title_activity_main"]
       replace: |
         <string name="title_activity_main">Capacitor App</string>

     - resFile: values/strings.xml
       target: resources/string[@name="package_name"]
       replace: |
         <string name="package_name">boy</string>

     - resFile: values/strings.xml
       target: resources/string[@name="custom_url_scheme"]
       replace: |
         <string name="package_name">boy</string>
  ios:
    targets:
      App:
        version: 1.0.0
        buildNumber: 1
        bundleId: boy
        displayName: Capacitor App
        productName: Capacitor App
        buildSettings:
          INFOPLIST_KEY_CFBundleDisplayName: Capacitor App

     